name: AutoZipAndRelease
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create Release Folder
      run: rsync -arv --exclude '.git' --exclude '.github' --exclude '.gitattributes' --exclude '.gitignore' --exclude 'README.md' . ./release
    - name: Switch to Release Folder
      run: |
        cd release
        ls -la
    - name: Bump version and push tag
      uses: alexeyatbluescape/github-tag-action@bugfix/semver-empty-results
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        REPO_OWNER: Paloys
        WITH_V: true
        RELEASE_BRANCHES: master
        DEFAULT_BUMP: patch
